### PR TITLE
Added tests for checkSystem

### LINKED ISSUE #8: create unit tests

### PR DESCRIPTION
**Pull request by YashdalfTheGray**
This closes #8 and #18. This depends on #17 so that should be merged first. 

Changes:
- (feature) pulled in `tape` to test and `tap-min` to minimally print test results
- (feature) added tests for the `checkSystem` module
- (feature) added a simple `.travis.yml` so that we can enable CI
- (feature) added a utility called `MockFile` that helps with testing different engine objects

I ignored writing tests for the `validatorRules` module since it seemed pretty simple and didn't have too much logic. 

Once the travis file is in, follow the steps [here](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A) to enable travis for the main repo. Step 3 is already done. It will automatically build for any commits or PRs to any branch on the repo and email the author if failed. 

The current status of the Travis build for this branch can be checked [here](https://travis-ci.org/YashdalfTheGray/checker.js/builds/166916337).

### CODE REVIEW

**Review by mohlsen — CHANGES_REQUESTED** [review]
I think a better way to do the mocks in the test would be to use https://www.npmjs.com/package/mock-require and / or https://www.npmjs.com/package/proxyquire to accomplish this without writing to the file system.

**Comment by mohlsen** [comment]
Something also seems weird too, cause changes from PR #2  are showing up here as changes.  Maybe just GitHub thing?

**Comment by mohlsen** [comment]
Awesome on CI and Travis

**Comment by YashdalfTheGray** [comment]
Alright, removed dependency on the file system and started using `proxyquire` instead. [Tests still pass!](https://travis-ci.org/YashdalfTheGray/checker.js/builds/166916337)

**Review by mohlsen — COMMENTED** [review]
👍

**Pull request merged**
